use std::io::Error;

fn main() -> Result<(), Error> {
    ray_rs::run()
}
